apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: watch-services-endpoints
  namespace: default
rules:
- apiGroups: [""]
  resources: ["services", "endpoints"]
  verbs: ["watch", "list", "get"]


