apiVersion: apps/v1
kind: Deployment
metadata: 
  name: postgres16
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: postgres16
  template: 
    metadata: 
      labels: 
        app: postgres16
    spec: 
      containers: 
        - image: postgres:16beta3-alpine3.18
          name: postgres16
          ports: 
            - containerPort: 5432
          env: 
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_DB
              value: droid_users
          volumeMounts:
            - name: data-postgres
              mountPath: /var/lib/postgresql/data
      volumes: 
        - name: data-postgres
          hostPath:
            path: /var/lib/postgresql/data
            type: DirectoryOrCreate
