apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql8
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mysql8
  template:
    metadata:
      labels:
        app: mysql8
    spec:
      containers:
      - image: mysql:8.0.18
        name: mysql8
        ports:
        - containerPort: 3306
        env: 
          - name: MYSQL_ROOT_PASSWORD
            value: mysql
          - name: MYSQL_DATABASE
            value: droid_news

