apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql8
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql8
  template:
    metadata:
      labels:
        app: mysql8
    spec:
      containers:
        - image: mysql:8.0.18
          name: mysql8
          ports:
            - containerPort: 3306
          env: 
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret-droid-news-news
                  key: password
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: configmap-droid-news-news
                  key: database
          volumeMounts:
            - name: data-mysql
              mountPath: /var/lib/mysql
      volumes: 
        - name: data-mysql
          persistentVolumeClaim:
            claimName: pvc-mysql

