version: "3.9"

services:
  postgres16:
    container_name: postgres16
    image: postgres:16beta3-alpine3.18
    ports:
      - "5532:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: droid_users
    volumes:
      - data-postgres:/var/lib/postgresql/data
    restart: always
    networks:
      - rede-droid

  mysql8:
    container_name: mysql8
    image: mysql:8.0.18
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: droid_news
    volumes:
      - data-mysql:/var/lib/mysql
    restart: always
    networks:
      - rede-droid

  droid-news-users:
    container_name: users
    build:
      context: ./
      dockerfile: ./droid-news-users/Dockerfile
    ports:
      - "8001:8001"
    # env_file: ./droid-news-users/.env
    environment:
      PORT: 8001
      DB_HOST: postgres16:5432
      DB_DATABASE: droid-users
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      NEWS_URL: news:8002
    restart: always
    networks:
      - rede-droid
    depends_on:
      - postgres16

  droid-news-news:
    container_name: news
    build:
      context: ./
      dockerfile: ./droid-news-news/Dockerfile
    ports:
      - "8002:8002"
    # env_file: ./droid-news-news/.env
    environment:
      PORT: 8002
      DB_HOST: mysql8:3306
      DB_DATABASE: droid-news
      DB_USERNAME: root 
      DB_PASSWORD: mysql 
      USERS_URL: users:8001
    restart: always
    networks:
      - rede-droid
    depends_on:
      - mysql8
      - droid-news-users

volumes:
  data-mysql:
    name: data-mysql
  data-postgres:
    name: data-postgres

networks:
  rede-droid:
    name: rede-droid
