version: "3.9"

services:
  postgres16:
    image: postgres:16beta3-alpine3.18
    ports:
      - "3307:3306"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: droid_users
    volumes:
      - data-postgres:/var/lib/postgresql/data
    restart: always
    networks:
      - rede-droid

  mysql8:
    image: mysql:8.0.18
    ports:
      - "5532:5432"
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: droid_news
    volumes:
      - data-mysql:/var/lib/mysql
    restart: always
    networks:
      - rede-droid

  droid-news-users:
    container_name: users
    image: droid-news-users:v1
    ports:
      - "8001:8001"
    env_file: .\droid-news-users\.env
    restart: always
    networks:
      - rede-droid
    depends_on:
      - postgres16

  droid-news-news:
    container_name: news
    image: droid-news-news:v1
    ports:
      - "8002:8002"
    env_file: .\droid-news-news\.env
    restart: always
    networks:
      - rede-droid
    depends_on:
      - mysql8

volumes:
  data-mysql:
    name: data-mysql
  data-postgres:
    name: data-postgres

networks:
  rede-droid:
