apiVersion: v1
kind: Secret
metadata:
  name: droid-news-users
type: Opaque
data:
  username: cG9zdGdyZXM=
  password: cG9zdGdyZXM=

---
apiVersion: v1
kind: Secret
metadata:
  name: droid-news-news
type: Opaque
data:
  username: cm9vdA==
  password: bXlzcWw=

