apiVersion: v1
kind: Service
metadata: 
  name: droid-news-news
spec: 
  ports: 
    - port: 8002
      protocol: TCP
      targetPort: 8002
  selector: 
    app: droid-news-news
  type: LoadBalancer

