spring:
  cloud:
    gateway:
      routes:
        - id: users
          uri: lb://users
          predicates:
            - Path=/api/v1/users/**
          filters:
            - StripPrefix=3
        - id: news
          uri: lb://news
          predicates:
            - Path=/api/v1/news/**
          filters:
            - StripPrefix=3
        - id: blue
          uri: lb://blue
          predicates:
            - Path=/api/v1/blue/**
          filters:
            - StripPrefix=3

