apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-users
data:
  port: "9011"
  db_host: postgres16:5432
  database: droid_users
  # username: postgres
  # password: postgres
  news_url: news:9012

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-news
data:
  port: "9012"
  db_host: mysql8:3306
  database: droid_news
  # username: root
  # password: mysql
  users_url: users:9011

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-blue
data:
  port: "9014"
  db_host: mongo7:27017
  database: droid_blue

