apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo7
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo7
  template:
    metadata:
      labels:
        app: mongo7
    spec:
      containers:
        - image: mongo:latest
          name: mongo7
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: configmap-blue
                  key: database
          volumeMounts:
            - name: data-mongo
              mountPath: /data/db
      volumes:
        - name: data-mongo
          persistentVolumeClaim:
            claimName: pvc-mongo
