apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: watch-services-endpoints-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
roleRef:
  kind: Role
  name: watch-services-endpoints
  apiGroup: rbac.authorization.k8s.io


